# Generated by Django 6.1.1 on 2026-09-19 23:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('vocabulary_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('grammar_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('listening_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('reading_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('writing_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('speaking_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('weakest_skill', models.CharField(blank=True, max_length=20, null=True)),
                ('strongest_skill', models.CharField(blank=True, max_length=20, null=True)),
                ('exams_completed', models.PositiveIntegerField(default=0)),
                ('questions_answered', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('accuracy', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('study_minutes', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
