# Generated by Django 6.1.1 on 2026-09-19 22:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weakest_skill', models.CharField(blank=True, choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('LISTENING', 'Listening'), ('READING', 'Reading'), ('WRITING', 'Writing'), ('SPEAKING', 'Speaking')], max_length=20, null=True)),
                ('strongest_skill', models.CharField(blank=True, choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('LISTENING', 'Listening'), ('READING', 'Reading'), ('WRITING', 'Writing'), ('SPEAKING', 'Speaking')], max_length=20, null=True)),
                ('vocabulary_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('grammar_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('listening_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('reading_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('writing_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('speaking_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AdaptiveRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('LISTENING', 'Listening'), ('READING', 'Reading'), ('WRITING', 'Writing'), ('SPEAKING', 'Speaking')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-score', '-created_at'],
            },
        ),
    ]
