# Generated by Django 6.1.1 on 2026-09-19 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('definition', models.TextField()),
                ('example_sentence', models.TextField(blank=True)),
                ('translation', models.CharField(blank=True, max_length=255)),
                ('difficulty', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('part_of_speech', models.CharField(blank=True, max_length=50)),
                ('pronunciation', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['difficulty', 'word'],
                'constraints': [models.UniqueConstraint(fields=('word', 'difficulty'), name='unique_vocabulary_word_difficulty')],
            },
        ),
        migrations.CreateModel(
            name='VocabularyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('LEARNING', 'Learning'), ('MASTERED', 'Mastered')], default='NEW', max_length=20)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('incorrect_answers', models.PositiveIntegerField(default=0)),
                ('last_answer_correct', models.BooleanField(blank=True, null=True)),
                ('mastery_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_progress', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='vocabulary.vocabularyword')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'word'), name='unique_vocabulary_progress_per_user')],
            },
        ),
    ]
