# Generated by Django 6.1.1 on 2026-09-19 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('LISTENING', 'Listening'), ('READING', 'Reading'), ('WRITING', 'Writing'), ('SPEAKING', 'Speaking'), ('MIXED', 'Mixed')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('target_minutes', models.PositiveIntegerField(default=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('LISTENING', 'Listening'), ('READING', 'Reading'), ('WRITING', 'Writing'), ('SPEAKING', 'Speaking')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_count', models.PositiveIntegerField(default=1)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('incorrect_count', models.PositiveIntegerField(default=0)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='learning.learningsession')),
            ],
            options={
                'ordering': ['session', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('session', 'order'), name='unique_learning_activity_order_per_session')],
            },
        ),
    ]
