# Generated by Django 6.1.1 on 2026-09-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningactivity',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='learningactivity',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='learningactivity',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
