# Generated by Django 6.1.1 on 2026-09-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('LISTENING', 'Listening'), ('READING', 'Reading')], max_length=20)),
                ('question_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('TRUE_FALSE_NOT_GIVEN', 'True / False / Not Given'), ('YES_NO_NOT_GIVEN', 'Yes / No / Not Given'), ('MATCHING', 'Matching'), ('FILL_GAP', 'Fill in the Gap')], max_length=30)),
                ('text', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.TextField()),
                ('points', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=1)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['skill', 'order', 'id'],
            },
        ),
    ]
