# Generated by Django 6.1.1 on 2026-09-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examsection'),
        ('questions', '0002_question_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['section', 'order', 'id']},
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('section', 'order'), name='unique_question_order_per_section'),
        ),
    ]
