# Generated by Django 6.1.1 on 2026-09-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=165),
        ),
    ]
